### ISSUE TITLE
人脸特征点不准确

### ISSUE THREAD

**Issue by dinghuawen** [zye1996/Mobilefacenet-TF2-coral_tpu#1]
你好， 我使用了你工程中的模型在coral dev上进行人脸检测，发现人脸特征点总是不准确，但是我看你附的视频中挺准确的，请问这可能会是什么原因导致的？谢谢！ 我使用的图像大小是320*240，使用tpu进行推断[
![faceimg](https://user-images.githubusercontent.com/20460515/98146492-8d8c9e80-1f06-11eb-8112-c9e03e8bed61.jpg)

**Comment by zye1996** [comment]
> 你好， 我使用了你工程中的模型在coral dev上进行人脸检测，发现人脸特征点总是不准确，但是我看你附的视频中挺准确的，请问这可能会是什么原因导致的？谢谢！ 我使用的图像大小是320*240，使用tpu进行推断[
> ![faceimg](https://user-images.githubusercontent.com/20460515/98146492-8d8c9e80-1f06-11eb-8112-c9e03e8bed61.jpg)
在postprocessing这个文件中有计算人脸检测点的代码，模型回归出的特征点需要乘上variance才得到图片中的结果，你可以再看看是不是有这一步后处理
